// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjzQHm-I7DJbW9MYKeA2q2oWePC6bojiQ',
    appId: '1:838699599098:web:cd9ebe01080c88f00db543',
    messagingSenderId: '838699599098',
    projectId: 'alwadifood-462c6',
    authDomain: 'alwadifood-462c6.firebaseapp.com',
    storageBucket: 'alwadifood-462c6.firebasestorage.app',
    measurementId: 'G-VDSDYM32NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKYPSqHgMQCoWGokpNLXPE-yRdIaINlAs',
    appId: '1:838699599098:android:0ea36b45e3b470590db543',
    messagingSenderId: '838699599098',
    projectId: 'alwadifood-462c6',
    storageBucket: 'alwadifood-462c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4OmAWYAQZuRSgwReiN81Fhprp4LxFOG0',
    appId: '1:838699599098:ios:211d4dd83fe5bdbf0db543',
    messagingSenderId: '838699599098',
    projectId: 'alwadifood-462c6',
    storageBucket: 'alwadifood-462c6.firebasestorage.app',
    iosBundleId: 'com.example.alwadiFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4OmAWYAQZuRSgwReiN81Fhprp4LxFOG0',
    appId: '1:838699599098:ios:211d4dd83fe5bdbf0db543',
    messagingSenderId: '838699599098',
    projectId: 'alwadifood-462c6',
    storageBucket: 'alwadifood-462c6.firebasestorage.app',
    iosBundleId: 'com.example.alwadiFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjzQHm-I7DJbW9MYKeA2q2oWePC6bojiQ',
    appId: '1:838699599098:web:29ed72d65407ee050db543',
    messagingSenderId: '838699599098',
    projectId: 'alwadifood-462c6',
    authDomain: 'alwadifood-462c6.firebaseapp.com',
    storageBucket: 'alwadifood-462c6.firebasestorage.app',
    measurementId: 'G-FT16EWP5H2',
  );
}
